<a href="https://colab.research.google.com/github/hazelhkim/Blockchain_App/blob/master/Copy_of_train_lexGAT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
downloaded = drive.CreateFile({'id':'13EyPZjDJVjgeAhlx5icKZpf1aEBzHzXK'})
downloaded.GetContentFile('movie_metadata.csv')

In [0]:
import pandas as pd
dt = pd.read_csv('movie_metadata.csv') 
print(dt.head(1))

   color  director_name  ...  aspect_ratio  movie_facebook_likes
0  Color  James Cameron  ...          1.78                 33000

[1 rows x 28 columns]


In [0]:
from google.colab import files
files.upload()

Saving edges.pkl to edges.pkl


{'edges.pkl': b'\x80\x03]q\x00(cscipy.sparse.csr\ncsr_matrix\nq\x01)\x81q\x02}q\x03(X\x06\x00\x00\x00_shapeq\x04M\xe41M\xe41\x86q\x05X\x08\x00\x00\x00maxprintq\x06K2X\x04\x00\x00\x00dataq\x07cnumpy.core.multiarray\n_reconstruct\nq\x08cnumpy\nndarray\nq\tK\x00\x85q\nC\x01bq\x0b\x87q\x0cRq\r(K\x01M5\x12\x85q\x0ecnumpy\ndtype\nq\x0fX\x02\x00\x00\x00f8q\x10K\x00K\x01\x87q\x11Rq\x12(K\x03X\x01\x00\x00\x00<q\x13NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x14b\x89B\xa8\x91\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0

In [0]:
import pickle
edges = open('edges.pkl', 'rb')
edges = pickle.load(edges)
MD = edges[0]
DM = edges[1]
AM = edges[2]
MA = edges[3]

In [0]:
from google.colab import files
files.upload()

Saving labels.pkl to labels.pkl


{'labels.pkl': b'\x80\x03]q\x00(]q\x01(]q\x02(Ms\x11K\x02e]q\x03(M\xdb\x11K\x02e]q\x04(M\x19\x0fK\x02e]q\x05(MN\tK\x00e]q\x06(M\x17\x08K\x02e]q\x07(M\xa7\x0cK\x01e]q\x08(M\x9f\x0bK\x01e]q\t(M\xeb\x0fK\x01e]q\n(M\xcd\nK\x02e]q\x0b(K\x1dK\x00e]q\x0c(M\xa7\tK\x02e]q\r(M\x93\x11K\x01e]q\x0e(M\x8e\x06K\x01e]q\x0f(M\xce\x01K\x02e]q\x10(M\x8c\nK\x02e]q\x11(M+\x07K\x02e]q\x12(MO\x07K\x01e]q\x13(K\xd9K\x00e]q\x14(M\xa6\x06K\x00e]q\x15(M\x87\x07K\x01e]q\x16(M|\rK\x00e]q\x17(ML\x02K\x00e]q\x18(MK\x08K\x02e]q\x19(M\xe1\x0eK\x02e]q\x1a(M\x0c\x04K\x02e]q\x1b(Md\x06K\x01e]q\x1c(Ms\x05K\x00e]q\x1d(M\xa8\x11K\x02e]q\x1e(M\x03\x11K\x02e]q\x1f(M\xf4\x06K\x02e]q (M\x80\x0eK\x01e]q!(M\xf0\x10K\x01e]q"(M4\x02K\x01e]q#(M\xee\nK\x01e]q$(Mz\x04K\x02e]q%(M\xd4\x01K\x00e]q&(M\xdb\x05K\x01e]q\'(M\xf7\tK\x02e]q((K\x7fK\x00e]q)(M\x9f\x05K\x00e]q*(K<K\x02e]q+(M\x04\x07K\x00e]q,(MP\rK\x02e]q-(M\x0e\nK\x02e]q.(M-\x01K\x02e]q/(M\x81\x02K\x00e]q0(M\xc9\x08K\x00e]q1(M\xf1\x0eK\x02e]q2(Ms\nK\x01e]q3(M\xa8\x05K\x02e]q4(M\x

In [0]:
labels = open('labels.pkl', 'rb')
labels = pickle.load(labels)
train = labels[0]
val = labels[1]
test = labels[2]

In [0]:
files.upload()

Saving node_features.pkl to node_features.pkl


In [0]:
node_features = open('node_features.pkl','rb')
node_features = pickle.load(node_features)
print(node_features)

[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


### **Implement GAT layer**

In [0]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

class GraphAttentionLayer(nn.Module):
    def __init__(self, in_features, out_features, dropout, alpha, concat=True):
        super(GraphAttentionLayer, self).__init__()
        self.dropout = dropout
        self.in_features = in_features
        self.out_features = out_features
        self.alpha = alpha
        self.concat = concat

        self.W = nn.Parameter(torch.zeros(size=(in_features, out_features)))
        nn.init.xavier_uniform_(self.W.data, gain=1.414)
        self.a = nn.Parameter(torch.zeros(size=(2*out_features, 1)))
        nn.init.xavier_uniform_(self.a.data, gain=1.414)

        self.leakyrelu = nn.LeakyReLU(self.alpha)

    def forward(self, input, adj):
        h = torch.mm(input, self.W)
        N = h.size()[0]

        a_input = torch.cat([h.repeat(1, N).view(N * N, -1), h.repeat(N, 1)], dim=1).view(N, -1, 2 * self.out_features)
        e = self.leakyrelu(torch.matmul(a_input, self.a).squeeze(2))

        zero_vec = -9e15*torch.ones_like(e)
        attention = torch.where(adj > 0, e, zero_vec)
        attention = F.softmax(attention, dim=1)
        attention = F.dropout(attention, self.dropout, training=self.training)
        h_prime = torch.matmul(attention, h)

        if self.concat:
            return F.elu(h_prime)
        else:
            return h_prime


### **Import pyGAT modules**

In [16]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


In [17]:
!pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html

Looking in links: https://pytorch-geometric.com/whl/torch-1.4.0.html
     |████████████████████████████████| 10.6MB 7.7MB/s 
  Found existing installation: torch-scatter 2.0.4
    Uninstalling torch-scatter-2.0.4:
      Successfully uninstalled torch-scatter-2.0.4


In [18]:
!pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
!pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html
!pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.4.0.html

Looking in links: https://pytorch-geometric.com/whl/torch-1.4.0.html
     |████████████████████████████████| 15.2MB 205kB/s 
  Found existing installation: torch-sparse 0.6.1
    Uninstalling torch-sparse-0.6.1:
      Successfully uninstalled torch-sparse-0.6.1
Looking in links: https://pytorch-geometric.com/whl/torch-1.4.0.html
     |████████████████████████████████| 14.5MB 239kB/s 
  Found existing installation: torch-cluster 1.5.4
    Uninstalling torch-cluster-1.5.4:
      Successfully uninstalled torch-cluster-1.5.4
Looking in links: https://pytorch-geometric.com/whl/torch-1.4.0.html
     |████████████████████████████████| 5.1MB 6.6MB/s 
  Found existing installation: torch-spline-conv 1.2.0
    Uninstalling torch-spline-conv-1.2.0:
      Successfully uninstalled torch-spline-conv-1.2.0


In [19]:
!pip install torch-geometric
from torch_geometric.data import Data
from torch_geometric.nn import GATConv
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T

import matplotlib.pyplot as plt
%matplotlib notebook

import warnings
warnings.filterwarnings("ignore")

RuntimeError: ignored

In [1]:
name_data = 'Cora'
dataset = Planetoid(root= '/tmp/' + name_data, name = name_data)
dataset.transform = T.NormalizeFeatures()

print(f"Number of Classes in {name_data}:", dataset.num_classes)
print(f"Number of Node Features in {name_data}:", dataset.num_node_features)

NameError: ignored

### **Implement the model**

In [0]:
class GAT(nn.Module):
    def __init__(self, nfeat, nhid, nclass, dropout, alpha, nheads):
        """Dense version of GAT."""
        super(GAT, self).__init__()
        self.dropout = dropout

        self.attentions = [GraphAttentionLayer(nfeat, nhid, dropout=dropout, alpha=alpha, concat=True) for _ in range(nheads)]
        for i, attention in enumerate(self.attentions):
            self.add_module('attention_{}'.format(i), attention)

        self.out_att = GraphAttentionLayer(nhid * nheads, nclass, dropout=dropout, alpha=alpha, concat=False)

    def forward(self, x, adj):
        x = F.dropout(x, self.dropout, training=self.training)
        x = torch.cat([att(x, adj) for att in self.attentions], dim=1)
        x = F.dropout(x, self.dropout, training=self.training)
        x = F.elu(self.out_att(x, adj))
        return F.log_softmax(x, dim=1)

### **Train**

In [0]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GAT().to(device)

### **Evaluate**